apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
      annotations:
        ad.datadoghq.com/server.logs: '[{"source":"go","service":"productcatalogservice", "sourcecategory":"sourcecode", "file":"file"}]'
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: productcatalogservice
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: MONGO_URL
          value: mongodb://mongo:27017/dev
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: "prod"
        - name: DD_SERVICE
          value: "productcatalogservice"
        - name: DD_VERSION
          value: "1.0.0"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
