apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
      annotations:
        ad.datadoghq.com/server.logs: '[{"source":"go","service":"shippingservice", "sourcecategory":"sourcecode", "file":"file"}]'
    spec:
      containers:
      - name: server
        image: shippingservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: "prod"
        - name: DD_SERVICE
          value: "shippingservice"
        - name: DD_VERSION
          value: "1.0.0"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          # requests:
          #   cpu: 100m
          #   memory: 64Mi
          # limits:
          #   cpu: 200m
          #   memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
